// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "The Sun",
  category: "Housing society",
  address: "\nNr. Marriott Hills, Bhakti Circle, opp. Patel Samaj Wadi, Ankur Chokadi, New India Colony, Ankur Tenament, Nikol, Ahmedabad, Gujarat 380049",
  phone: "",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/place/The+Sun/@23.0536551,72.6766025,3a,75y,90t/data=!3m8!1e2!3m6!1sCIABIhAe1p-xkdlBSscrRzA-dmC9!2e10!3e12!6shttps:%2F%2Flh3.googleusercontent.com%2Fgps-cs-s%2FAPNQkAHpMBAhs5A6Dc8ZrEuJYrBA5fuNGhNg5xRCRJXqn06_4dMWzsxzzpDk-b3KRjgfJdvI_9l51HR0JbanqWqRtWL3UwILYQVDZ9bNe_AUmz12ccW9wRiucs6PS8TcDCKoFnn7Lov0BqTH5LIY%3Dw146-h86-k-no!7i2560!8i1506!4m6!3m5!1s0x395e872c2307f1bd:0x25b3346b6e1e70cf!8m2!3d23.053658!4d72.6766202!16s%2Fg%2F11yt2kr520?entry=ttu&g_ep=EgoyMDI2MDUyNy4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0536551",
  longitude: "72.6766025",
  rating: "",
  reviewsCount: "3",
  openingHours: "Show open hours for the week",
  logo: null,
  images: ["/images/gmap_1780033150975_0.jpg", "/images/gmap_1780033151512_1.jpg", "/images/gmap_1780033151929_2.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Nikol's Premier Housing Society",
  heroDescription: "Experience the best of Nikol at The Sun, a premium housing society located near Marriott Hills. With modern designs and spacious layouts, our homes are perfect for those looking for a comfortable and luxurious living experience. Our society is nestled in the heart of Ahmedabad, providing easy access to all major amenities.",
  aboutTitle: "A New Era of Living",
  aboutText: "The Sun is a housing society like no other, situated in the vibrant area of Nikol, near Bhakti Circle and Patel Samaj Wadi. Our address,  Nr. Marriott Hills, Bhakti Circle, opp. Patel Samaj Wadi, Ankur Chokadi, New India Colony, Ankur Tenament, Nikol, Ahmedabad, Gujarat 380049, offers the perfect blend of convenience and tranquility. With a focus on providing top-notch amenities and services, we strive to create a community that is truly exceptional. Our mission is to provide a comfortable and secure living environment for our residents, making The Sun the perfect choice for those looking for a premium housing society in Ahmedabad.",
  services: [
    { icon: "🏠", title: "Spacious Layouts", description: "Our homes feature modern designs and spacious layouts, perfect for families and individuals alike. Prices start from ₹601 per sq. ft." },
    { icon: "🏞️", title: "Lush Green Spaces", description: "Our society boasts lush green spaces and beautifully landscaped gardens, providing a serene escape from the hustle and bustle of city life. Maintenance costs are ₹1200 per month." },
    { icon: "🏋️‍♀️", title: "State-of-the-Art Gym", description: "Stay fit and healthy with our state-of-the-art gym, equipped with the latest equipment and trained professionals. Membership fees are ₹4252 per year." },
    { icon: "🚗", title: "Secure Parking", description: "Our society features secure parking facilities, ensuring the safety and security of your vehicles. Parking fees are ₹800 per month." },
    { icon: "👮", title: "24/7 Security", description: "Our society is equipped with 24/7 security, providing a safe and secure living environment for our residents. Security deposit is ₹2000." },
    { icon: "📚", title: "Community Center", description: "Our community center is the perfect place to socialize and connect with your neighbors, featuring a library, game room, and more. Membership fees are ₹1000 per year." }
  ],
  whyChooseUs: [
    { icon: "🏙️", title: "Prime Location", description: "Our society is located in the heart of Nikol, providing easy access to all major amenities and transportation hubs." },
    { icon: "👥", title: "Community Focus", description: "We strive to create a sense of community among our residents, with regular events and activities to promote socializing and connection." },
    { icon: "💡", title: "Innovative Designs", description: "Our homes feature modern and innovative designs, providing a unique and comfortable living experience." },
    { icon: "🏥", title: "Proximity to Amenities", description: "Our society is located near major hospitals, schools, and shopping centers, providing easy access to all your needs." }
  ],
  testimonials: [
    { name: "darshan savaliya", role: "Google Review", text: "Excellent project with premium construction quality. The Sun offers spacious layouts, modern design, and a great location in Nikol. Very satisfied with the overall experience.", rating: 5 },
    { name: "Nikhil Mittaliya", role: "Google Review", text: "One of the best premium flats in nikol", rating: 5 }
  ],
  faq: { items: [{ question: "What are the prices of the homes at The Sun?", answer: "Our homes start from ₹601 per sq. ft. and go up to ₹4252 per sq. ft. depending on the size and amenities." },
    { question: "What amenities does The Sun offer?", answer: "Our society features a state-of-the-art gym, secure parking, 24/7 security, community center, and lush green spaces." },
    { question: "Is The Sun located near major transportation hubs?", answer: "Yes, our society is located near major transportation hubs, making it easy to commute to work, school, or other destinations." },
    { question: "What is the process for booking a home at The Sun?", answer: "To book a home at The Sun, please contact our sales team to schedule a viewing and discuss pricing and availability." },
    { question: "Does The Sun have a community center?", answer: "Yes, our community center is a great place to socialize and connect with your neighbors, featuring a library, game room, and more." },
    { question: "What is the security deposit for a home at The Sun?", answer: "The security deposit for a home at The Sun is ₹2000." }] },
  ctaTitle: "Experience The Sun",
  ctaDescription: "Join our community today and experience the best of Nikol. Contact us to schedule a viewing and learn more about our homes and amenities.",
  ctaButtonText: "Book a Tour",
  metaDescription: "The Sun: Nikol's premier housing society",
};

export const siteConfig = {
  layout: "monochrome",
  theme: "elegant",
  sections: ["testimonials", "faq", "about", "gallery", "contact", "services"],
  heroVariant: "left-aligned-content",
  navStyle: "hamburger-menu",
  animationStyle: "parallax-sections",
  cardStyle: "rounded-2xl backdrop-blur-md bg-white/5 border border-white/10",
  darkMode: true,
};
